// Mock data for events
export interface Event {
  id: string;
  title: string;
  date: string;
  description: string;
  location: string;
  category: string;
  organizer: string;
  image: string;
  participants: Participant[];
  status: "past" | "ongoing" | "upcoming";
  attendeesCount: number;
}

export interface Participant {
  id: string;
  name: string;
  email: string;
  role: string;
  position?: string; // HR Officer, Manager, Employee, etc.
  avatar?: string;
  checkedIn?: boolean; // Whether they have checked in to the event
}

export interface Feedback {
  id: string;
  eventId: string;
  participantId: string;
  participantName: string;
  participantEmail: string;
  rating: number;
  feedbackCategories: {
    venue: string;
    content: string;
    organization: string;
    overall: string;
  };
  recommendation: string;
  comments: string;
  improvements: string;
  submittedAt: string;
}

export const pastEvents: Event[] = [
  {
    id: "1",
    title: "Music in the Park: Summer Concert Series",
    date: "2024-10-15",
    description:
      "A comprehensive technology summit featuring the latest innovations in AI, cloud computing, and software development.",
    location: "Central Park, New York City, United States",
    category: "Dance & Music",
    organizer: "World Fusion Events",
    image: "/events/img1.jpg", // Place in public/events/
    status: "past",
    attendeesCount: 1200,
    participants: [
      {
        id: "p1",
        name: "John Doe",
        email: "john@example.com",
        role: "Attendee",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
      },
      {
        id: "p2",
        name: "Jane Smith",
        email: "jane@example.com",
        role: "Speaker",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
      },
      {
        id: "p3",
        name: "Bob Johnson",
        email: "bob@example.com",
        role: "Organizer",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bob",
      },
      {
        id: "p4",
        name: "Alice Brown",
        email: "alice@example.com",
        role: "Attendee",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alice",
      },
    ],
  },
  {
    id: "2",
    title: "Tech Innovation Showcase",
    date: "2024-09-20",
    description:
      "An exhibition showcasing marketing strategies, digital campaigns, and brand management techniques.",
    location: "Silicon Valley Convention Center, CA",
    category: "Technology",
    organizer: "TechForward Inc",
    image: "/events/img2.jpg",
    status: "past",
    attendeesCount: 850,
    participants: [
      {
        id: "p5",
        name: "Charlie Wilson",
        email: "charlie@example.com",
        role: "Attendee",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Charlie",
      },
      {
        id: "p6",
        name: "Diana Prince",
        email: "diana@example.com",
        role: "Speaker",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Diana",
      },
      {
        id: "p7",
        name: "Eve Adams",
        email: "eve@example.com",
        role: "Attendee",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Eve",
      },
    ],
  },
  {
    id: "3",
    title: "Annual Gala Dinner",
    date: "2024-08-30",
    description:
      "A formal evening event celebrating achievements and networking with industry leaders.",
    location: "Grand Ballroom, Hotel Plaza",
    category: "Networking",
    organizer: "Elite Events Co",
    image: "/events/img3.jpeg",
    status: "past",
    attendeesCount: 300,
    participants: [
      {
        id: "p8",
        name: "Frank Miller",
        email: "frank@example.com",
        role: "VIP Guest",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Frank",
      },
      {
        id: "p9",
        name: "Grace Lee",
        email: "grace@example.com",
        role: "Attendee",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Grace",
      },
      {
        id: "p10",
        name: "Henry Davis",
        email: "henry@example.com",
        role: "Speaker",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Henry",
      },
      {
        id: "p11",
        name: "Ivy Chen",
        email: "ivy@example.com",
        role: "Organizer",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ivy",
      },
      {
        id: "p12",
        name: "Jack Taylor",
        email: "jack@example.com",
        role: "Attendee",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jack",
      },
    ],
  },
  {
    id: "4",
    title: "Startup Pitch Competition",
    date: "2024-07-15",
    description:
      "Entrepreneurs pitch their innovative ideas to investors and industry experts.",
    location: "Innovation Hub, Tech Park",
    category: "Business",
    organizer: "Venture Labs",
    image: "/events/img4.png",
    status: "past",
    attendeesCount: 450,
    participants: [
      {
        id: "p13",
        name: "Karen White",
        email: "karen@example.com",
        role: "Investor",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Karen",
      },
      {
        id: "p14",
        name: "Liam Garcia",
        email: "liam@example.com",
        role: "Entrepreneur",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Liam",
      },
      {
        id: "p15",
        name: "Mia Rodriguez",
        email: "mia@example.com",
        role: "Mentor",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mia",
      },
    ],
  },
];

export const ongoingEvents: Event[] = [
  {
    id: "5",
    title: "Summer Music Festival 2025",
    date: "2025-10-28",
    description:
      "Live outdoor music festival featuring top artists and bands across multiple genres. Experience incredible performances under the stars with state-of-the-art sound and lighting.",
    location: "Riverside Arena, Los Angeles, CA",
    category: "Dance & Music",
    organizer: "Festival Productions Ltd",
    image: "/events/ongoing1.png",
    status: "ongoing",
    attendeesCount: 2500,
    participants: [
      { id: "p16", name: "Sarah Johnson", email: "sarah.j@example.com", role: "Attendee", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah", checkedIn: true },
      { id: "p17", name: "Michael Chen", email: "michael.c@example.com", role: "VIP Guest", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael", checkedIn: true },
      { id: "p18", name: "Emily Rodriguez", email: "emily.r@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily", checkedIn: false },
      { id: "p19", name: "David Park", email: "david.p@example.com", role: "Staff", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=David", checkedIn: true },
      { id: "p27", name: "Jessica White", email: "jessica.w@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica", checkedIn: true },
      { id: "p28", name: "Chris Brown", email: "chris.b@example.com", role: "VIP Guest", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chris", checkedIn: false },
      { id: "p29", name: "Amanda Davis", email: "amanda.d@example.com", role: "Attendee", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amanda", checkedIn: true },
      { id: "p30", name: "Ryan Taylor", email: "ryan.t@example.com", role: "Staff", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ryan", checkedIn: true },
      { id: "p31", name: "Nicole Martinez", email: "nicole.m@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nicole", checkedIn: false },
      { id: "p32", name: "Kevin Anderson", email: "kevin.a@example.com", role: "VIP Guest", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin", checkedIn: true },
      { id: "p33", name: "Sophia Miller", email: "sophia.m@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophia", checkedIn: true },
      { id: "p34", name: "Daniel Wilson", email: "daniel.w@example.com", role: "Staff", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel", checkedIn: false },
      { id: "p35", name: "Emma Thomas", email: "emma.t@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma", checkedIn: true },
      { id: "p36", name: "Matthew Harris", email: "matthew.h@example.com", role: "VIP Guest", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Matthew", checkedIn: true },
      { id: "p37", name: "Olivia Clark", email: "olivia.c@example.com", role: "Attendee", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia", checkedIn: true },
      { id: "p38", name: "Joshua Lewis", email: "joshua.l@example.com", role: "Staff", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Joshua", checkedIn: false },
      { id: "p39", name: "Ava Robinson", email: "ava.r@example.com", role: "Attendee", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ava", checkedIn: true },
      { id: "p40", name: "Ethan Walker", email: "ethan.w@example.com", role: "VIP Guest", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ethan", checkedIn: true },
      { id: "p64", name: "Madison Scott", email: "madison.s@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Madison", checkedIn: false },
      { id: "p65", name: "Logan Hall", email: "logan.h@example.com", role: "VIP Guest", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Logan", checkedIn: true },
      { id: "p66", name: "Zoe Allen", email: "zoe.a@example.com", role: "Attendee", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Zoe", checkedIn: true },
      { id: "p67", name: "Jackson Young", email: "jackson.y@example.com", role: "Staff", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jackson", checkedIn: false },
      { id: "p68", name: "Aria King", email: "aria.k@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aria", checkedIn: true },
      { id: "p69", name: "Carter Wright", email: "carter.w@example.com", role: "VIP Guest", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carter", checkedIn: true },
      { id: "p70", name: "Layla Lopez", email: "layla.l@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Layla", checkedIn: false },
      { id: "p71", name: "Grayson Hill", email: "grayson.h@example.com", role: "Staff", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Grayson", checkedIn: true },
      { id: "p72", name: "Riley Green", email: "riley.g@example.com", role: "Attendee", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Riley", checkedIn: true },
      { id: "p73", name: "Wyatt Adams", email: "wyatt.a@example.com", role: "VIP Guest", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Wyatt", checkedIn: true },
      { id: "p74", name: "Penelope Baker", email: "penelope.b@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Penelope", checkedIn: false },
      { id: "p75", name: "Landon Nelson", email: "landon.n@example.com", role: "Staff", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Landon", checkedIn: true },
      { id: "p76", name: "Hazel Carter", email: "hazel.c@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hazel", checkedIn: true },
      { id: "p77", name: "Hudson Mitchell", email: "hudson.m@example.com", role: "VIP Guest", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hudson", checkedIn: false },
      { id: "p78", name: "Violet Perez", email: "violet.p@example.com", role: "Attendee", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Violet", checkedIn: true },
      { id: "p79", name: "Easton Roberts", email: "easton.r@example.com", role: "Staff", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Easton", checkedIn: true },
      { id: "p80", name: "Aurora Turner", email: "aurora.t@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aurora", checkedIn: true },
      { id: "p81", name: "Nolan Phillips", email: "nolan.p@example.com", role: "VIP Guest", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nolan", checkedIn: false },
      { id: "p82", name: "Savannah Campbell", email: "savannah.c@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Savannah", checkedIn: true },
      { id: "p83", name: "Ezra Parker", email: "ezra.p@example.com", role: "Staff", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ezra", checkedIn: true },
      { id: "p84", name: "Brooklyn Evans", email: "brooklyn.e@example.com", role: "Attendee", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Brooklyn", checkedIn: false },
      { id: "p85", name: "Colton Edwards", email: "colton.e@example.com", role: "VIP Guest", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Colton", checkedIn: true },
      { id: "p86", name: "Stella Collins", email: "stella.c@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Stella", checkedIn: true },
      { id: "p87", name: "Maverick Stewart", email: "maverick.s@example.com", role: "Staff", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maverick", checkedIn: true },
      { id: "p88", name: "Lucy Sanchez", email: "lucy.s@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucy", checkedIn: false },
      { id: "p89", name: "Brayden Morris", email: "brayden.m@example.com", role: "VIP Guest", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Brayden", checkedIn: true },
      { id: "p90", name: "Paisley Rogers", email: "paisley.r@example.com", role: "Attendee", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Paisley", checkedIn: true },
      { id: "p91", name: "Jaxon Reed", email: "jaxon.r@example.com", role: "Staff", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jaxon", checkedIn: false },
      { id: "p92", name: "Skylar Cook", email: "skylar.c@example.com", role: "Attendee", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Skylar", checkedIn: true },
      { id: "p93", name: "Axel Morgan", email: "axel.m@example.com", role: "VIP Guest", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Axel", checkedIn: true },
      { id: "p94", name: "Claire Bell", email: "claire.b@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Claire", checkedIn: true },
      { id: "p95", name: "Theo Murphy", email: "theo.m@example.com", role: "Staff", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Theo", checkedIn: false },
    ],
  },
  {
    id: "6",
    title: "Global Tech Summit 2025",
    date: "2025-10-28",
    description:
      "Premier technology conference bringing together industry leaders, innovators, and developers. Featuring keynote speeches, workshops, and networking sessions on AI, cloud computing, and emerging technologies.",
    location: "Tech Convention Center, San Francisco, CA",
    category: "Technology",
    organizer: "TechWorld Events",
    image: "/events/ongoing2.png",
    status: "ongoing",
    attendeesCount: 1800,
    participants: [
      { id: "p20", name: "Alex Thompson", email: "alex@example.com", role: "Speaker", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex", checkedIn: true },
      { id: "p21", name: "Jennifer Lee", email: "jennifer@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jennifer", checkedIn: true },
      { id: "p22", name: "Robert Kim", email: "robert@example.com", role: "Organizer", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Robert", checkedIn: true },
      { id: "p41", name: "Isabella Scott", email: "isabella@example.com", role: "Attendee", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella", checkedIn: false },
      { id: "p42", name: "William Young", email: "william@example.com", role: "Speaker", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=William", checkedIn: true },
      { id: "p43", name: "Mia King", email: "mia@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mia", checkedIn: true },
      { id: "p44", name: "Benjamin Wright", email: "benjamin@example.com", role: "Staff", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Benjamin", checkedIn: false },
      { id: "p45", name: "Charlotte Green", email: "charlotte@example.com", role: "VIP Guest", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Charlotte", checkedIn: true },
      { id: "p46", name: "Lucas Adams", email: "lucas@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas", checkedIn: true },
      { id: "p47", name: "Amelia Baker", email: "amelia@example.com", role: "Speaker", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amelia", checkedIn: true },
      { id: "p48", name: "Henry Nelson", email: "henry@example.com", role: "Attendee", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Henry", checkedIn: false },
      { id: "p49", name: "Harper Carter", email: "harper@example.com", role: "Staff", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Harper", checkedIn: true },
      { id: "p50", name: "Alexander Mitchell", email: "alexander@example.com", role: "VIP Guest", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alexander", checkedIn: true },
      { id: "p51", name: "Evelyn Perez", email: "evelyn@example.com", role: "Attendee", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Evelyn", checkedIn: true },
      { id: "p96", name: "Mason Rivera", email: "mason.r@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mason", checkedIn: false },
      { id: "p97", name: "Luna Cooper", email: "luna.c@example.com", role: "VIP Guest", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Luna", checkedIn: true },
      { id: "p98", name: "Elias Bailey", email: "elias.b@example.com", role: "Staff", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Elias", checkedIn: true },
      { id: "p99", name: "Nora Richardson", email: "nora.r@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nora", checkedIn: true },
      { id: "p100", name: "Julian Cox", email: "julian.c@example.com", role: "Speaker", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Julian", checkedIn: false },
      { id: "p101", name: "Mila Howard", email: "mila.h@example.com", role: "Attendee", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mila", checkedIn: true },
      { id: "p102", name: "Levi Ward", email: "levi.w@example.com", role: "VIP Guest", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Levi", checkedIn: true },
      { id: "p103", name: "Aria Torres", email: "aria.t@example.com", role: "Attendee", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=AriaT", checkedIn: false },
      { id: "p104", name: "Asher Peterson", email: "asher.p@example.com", role: "Staff", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Asher", checkedIn: true },
      { id: "p105", name: "Isla Gray", email: "isla.g@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Isla", checkedIn: true },
      { id: "p106", name: "Leo Ramirez", email: "leo.r@example.com", role: "Speaker", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Leo", checkedIn: true },
      { id: "p107", name: "Ivy James", email: "ivy.j@example.com", role: "VIP Guest", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ivy", checkedIn: false },
      { id: "p108", name: "Aaron Watson", email: "aaron.w@example.com", role: "Attendee", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aaron", checkedIn: true },
      { id: "p109", name: "Willow Brooks", email: "willow.b@example.com", role: "Staff", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Willow", checkedIn: true },
      { id: "p110", name: "Caleb Kelly", email: "caleb.k@example.com", role: "Attendee", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Caleb", checkedIn: true },
      { id: "p111", name: "Ruby Sanders", email: "ruby.s@example.com", role: "VIP Guest", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ruby", checkedIn: false },
      { id: "p112", name: "Nathan Price", email: "nathan.p@example.com", role: "Speaker", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nathan", checkedIn: true },
      { id: "p113", name: "Ellie Bennett", email: "ellie.b@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ellie", checkedIn: true },
      { id: "p114", name: "Connor Wood", email: "connor.w@example.com", role: "Staff", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Connor", checkedIn: false },
      { id: "p115", name: "Bella Barnes", email: "bella.b@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bella", checkedIn: true },
      { id: "p116", name: "Gavin Ross", email: "gavin.r@example.com", role: "VIP Guest", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Gavin", checkedIn: true },
      { id: "p117", name: "Naomi Henderson", email: "naomi.h@example.com", role: "Attendee", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Naomi", checkedIn: true },
      { id: "p118", name: "Dominic Coleman", email: "dominic.c@example.com", role: "Speaker", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dominic", checkedIn: false },
      { id: "p119", name: "Sophie Jenkins", email: "sophie.j@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie", checkedIn: true },
      { id: "p120", name: "Ian Perry", email: "ian.p@example.com", role: "Staff", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ian", checkedIn: true },
      { id: "p121", name: "Maya Powell", email: "maya.p@example.com", role: "VIP Guest", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maya", checkedIn: true },
      { id: "p122", name: "Tristan Long", email: "tristan.l@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tristan", checkedIn: false },
      { id: "p123", name: "Piper Patterson", email: "piper.p@example.com", role: "Speaker", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Piper", checkedIn: true },
      { id: "p124", name: "Micah Hughes", email: "micah.h@example.com", role: "Attendee", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Micah", checkedIn: true },
      { id: "p125", name: "Kinsley Flores", email: "kinsley.f@example.com", role: "VIP Guest", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kinsley", checkedIn: true },
      { id: "p126", name: "Bryson Washington", email: "bryson.w@example.com", role: "Staff", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bryson", checkedIn: false },
      { id: "p127", name: "Quinn Butler", email: "quinn.b@example.com", role: "Attendee", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Quinn", checkedIn: true },
      { id: "p160", name: "Sebastian Grant", email: "sebastian.g@example.com", role: "VIP Guest", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SebastianG", checkedIn: true },
      { id: "p161", name: "Raelynn Hunt", email: "raelynn.h@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Raelynn", checkedIn: false },
      { id: "p162", name: "Garrett Fox", email: "garrett.f@example.com", role: "Speaker", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Garrett", checkedIn: true },
      { id: "p163", name: "Adalyn Mills", email: "adalyn.m@example.com", role: "Attendee", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Adalyn", checkedIn: true },
    ],
  },
  {
    id: "7",
    title: "International Food & Culture Expo",
    date: "2025-10-28",
    description:
      "Celebrate global cuisines and cultural diversity at this vibrant food festival. Sample dishes from around the world, enjoy live cultural performances, and experience the flavors of different traditions.",
    location: "Downtown Square, Seattle, WA",
    category: "Food & Culture",
    organizer: "Cultural Events Association",
    image: "/events/ongoing3.png",
    status: "ongoing",
    attendeesCount: 3200,
    participants: [
      { id: "p23", name: "Maria Garcia", email: "maria@example.com", role: "Vendor", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maria", checkedIn: true },
      { id: "p24", name: "James Wilson", email: "james@example.com", role: "Attendee", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=James", checkedIn: true },
      { id: "p25", name: "Lisa Anderson", email: "lisa@example.com", role: "Performer", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa", checkedIn: false },
      { id: "p26", name: "Tom Martinez", email: "tom@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tom", checkedIn: true },
      { id: "p52", name: "Sebastian Roberts", email: "sebastian@example.com", role: "Vendor", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sebastian", checkedIn: true },
      { id: "p53", name: "Abigail Turner", email: "abigail@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Abigail", checkedIn: true },
      { id: "p54", name: "Jack Phillips", email: "jack@example.com", role: "Performer", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jack", checkedIn: false },
      { id: "p55", name: "Emily Campbell", email: "emily.c@example.com", role: "Staff", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=EmilyC", checkedIn: true },
      { id: "p56", name: "Owen Parker", email: "owen@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Owen", checkedIn: true },
      { id: "p57", name: "Scarlett Evans", email: "scarlett@example.com", role: "VIP Guest", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Scarlett", checkedIn: true },
      { id: "p58", name: "Liam Edwards", email: "liam@example.com", role: "Vendor", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Liam", checkedIn: false },
      { id: "p59", name: "Grace Collins", email: "grace@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Grace", checkedIn: true },
      { id: "p60", name: "Noah Stewart", email: "noah@example.com", role: "Performer", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Noah", checkedIn: true },
      { id: "p61", name: "Chloe Morris", email: "chloe@example.com", role: "Staff", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe", checkedIn: true },
      { id: "p62", name: "Elijah Rogers", email: "elijah@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Elijah", checkedIn: false },
      { id: "p63", name: "Lily Reed", email: "lily@example.com", role: "VIP Guest", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lily", checkedIn: true },
      { id: "p128", name: "Silas Simmons", email: "silas.s@example.com", role: "Vendor", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Silas", checkedIn: true },
      { id: "p129", name: "Leah Foster", email: "leah.f@example.com", role: "Attendee", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Leah", checkedIn: false },
      { id: "p130", name: "Wesley Gonzales", email: "wesley.g@example.com", role: "Performer", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Wesley", checkedIn: true },
      { id: "p131", name: "Aaliyah Bryant", email: "aaliyah.b@example.com", role: "Staff", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aaliyah", checkedIn: true },
      { id: "p132", name: "Roman Alexander", email: "roman.a@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Roman", checkedIn: true },
      { id: "p133", name: "Anna Russell", email: "anna.r@example.com", role: "VIP Guest", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Anna", checkedIn: false },
      { id: "p134", name: "Ryker Griffin", email: "ryker.g@example.com", role: "Vendor", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ryker", checkedIn: true },
      { id: "p135", name: "Caroline Diaz", email: "caroline.d@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Caroline", checkedIn: true },
      { id: "p136", name: "Kai Hayes", email: "kai.h@example.com", role: "Performer", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kai", checkedIn: true },
      { id: "p137", name: "Vivian Myers", email: "vivian.m@example.com", role: "Staff", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Vivian", checkedIn: false },
      { id: "p138", name: "River Ford", email: "river.f@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=River", checkedIn: true },
      { id: "p139", name: "Eliana Hamilton", email: "eliana.h@example.com", role: "VIP Guest", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Eliana", checkedIn: true },
      { id: "p140", name: "Knox Graham", email: "knox.g@example.com", role: "Vendor", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Knox", checkedIn: false },
      { id: "p141", name: "Alice Sullivan", email: "alice.s@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alice", checkedIn: true },
      { id: "p142", name: "Beckett Wallace", email: "beckett.w@example.com", role: "Performer", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Beckett", checkedIn: true },
      { id: "p143", name: "Madelyn Woods", email: "madelyn.w@example.com", role: "Staff", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Madelyn", checkedIn: true },
      { id: "p144", name: "Gideon Cole", email: "gideon.c@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Gideon", checkedIn: false },
      { id: "p145", name: "Clara West", email: "clara.w@example.com", role: "VIP Guest", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Clara", checkedIn: true },
      { id: "p146", name: "Felix Jordan", email: "felix.j@example.com", role: "Vendor", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Felix", checkedIn: true },
      { id: "p147", name: "Delilah Owens", email: "delilah.o@example.com", role: "Attendee", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Delilah", checkedIn: true },
      { id: "p148", name: "Jasper Reynolds", email: "jasper.r@example.com", role: "Performer", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jasper", checkedIn: false },
      { id: "p149", name: "Emilia Fisher", email: "emilia.f@example.com", role: "Staff", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emilia", checkedIn: true },
      { id: "p150", name: "Atticus Ellis", email: "atticus.e@example.com", role: "Attendee", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Atticus", checkedIn: true },
      { id: "p151", name: "Iris Marshall", email: "iris.m@example.com", role: "VIP Guest", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Iris", checkedIn: false },
      { id: "p152", name: "Rowan Dixon", email: "rowan.d@example.com", role: "Vendor", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rowan", checkedIn: true },
      { id: "p153", name: "Violet Lawson", email: "violet.l@example.com", role: "Attendee", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=VioletL", checkedIn: true },
      { id: "p154", name: "Ezekiel Day", email: "ezekiel.d@example.com", role: "Performer", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ezekiel", checkedIn: true },
      { id: "p155", name: "Josephine Chapman", email: "josephine.c@example.com", role: "Staff", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Josephine", checkedIn: false },
      { id: "p156", name: "Finn Castillo", email: "finn.c@example.com", role: "Attendee", position: "Senior Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Finn", checkedIn: true },
      { id: "p157", name: "Genevieve Spencer", email: "genevieve.s@example.com", role: "VIP Guest", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Genevieve", checkedIn: true },
      { id: "p158", name: "August Webb", email: "august.w@example.com", role: "Vendor", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=August", checkedIn: true },
      { id: "p159", name: "Mariana Stone", email: "mariana.s@example.com", role: "Attendee", position: "HR Officer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mariana", checkedIn: false },
      { id: "p164", name: "Preston Black", email: "preston.b@example.com", role: "Performer", position: "Manager", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Preston", checkedIn: true },
      { id: "p165", name: "Khloe Knight", email: "khloe.k@example.com", role: "Attendee", position: "Employee", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Khloe", checkedIn: true },
    ],
  },
];

export const feedbackData: Feedback[] = [
  {
    id: "f1",
    eventId: "1",
    participantId: "p1",
    participantName: "John Doe",
    participantEmail: "john@example.com",
    rating: 5,
    feedbackCategories: {
      venue: "excellent",
      content: "excellent",
      organization: "excellent",
      overall: "excellent",
    },
    recommendation: "yes",
    comments: "Absolutely fantastic event! The music was incredible and the atmosphere was perfect. The park setting made it even more special.",
    improvements: "Maybe add more food options for vegetarians.",
    submittedAt: "2024-10-16T10:30:00Z",
  },
  {
    id: "f2",
    eventId: "1",
    participantId: "p4",
    participantName: "Alice Brown",
    participantEmail: "alice@example.com",
    rating: 4,
    feedbackCategories: {
      venue: "good",
      content: "excellent",
      organization: "good",
      overall: "very good",
    },
    recommendation: "yes",
    comments: "Great concert series! The lineup was amazing and the sound quality was excellent. Had a wonderful time with friends.",
    improvements: "The parking situation could be better organized.",
    submittedAt: "2024-10-16T14:20:00Z",
  },
  {
    id: "f3",
    eventId: "2",
    participantId: "p5",
    participantName: "Charlie Wilson",
    participantEmail: "charlie@example.com",
    rating: 5,
    feedbackCategories: {
      venue: "excellent",
      content: "excellent",
      organization: "excellent",
      overall: "excellent",
    },
    recommendation: "yes",
    comments: "This tech showcase was groundbreaking! The AI demonstrations were mind-blowing and the networking opportunities were invaluable.",
    improvements: "Would love to see more hands-on workshops next time.",
    submittedAt: "2024-09-21T09:15:00Z",
  },
  {
    id: "f4",
    eventId: "2",
    participantId: "p7",
    participantName: "Eve Adams",
    participantEmail: "eve@example.com",
    rating: 4,
    feedbackCategories: {
      venue: "good",
      content: "excellent",
      organization: "good",
      overall: "very good",
    },
    recommendation: "yes",
    comments: "Impressive showcase of innovations. The speakers were knowledgeable and the exhibits were well-curated.",
    improvements: "Some sessions ran over time, better time management would help.",
    submittedAt: "2024-09-21T16:45:00Z",
  },
  {
    id: "f5",
    eventId: "3",
    participantId: "p8",
    participantName: "Frank Miller",
    participantEmail: "frank@example.com",
    rating: 5,
    feedbackCategories: {
      venue: "excellent",
      content: "excellent",
      organization: "excellent",
      overall: "excellent",
    },
    recommendation: "yes",
    comments: "Elegant gala dinner with excellent networking opportunities. The food was outstanding and the speeches were inspiring.",
    improvements: "Everything was perfect, no suggestions for improvement.",
    submittedAt: "2024-08-31T22:00:00Z",
  },
  {
    id: "f6",
    eventId: "3",
    participantId: "p9",
    participantName: "Grace Lee",
    participantEmail: "grace@example.com",
    rating: 4,
    feedbackCategories: {
      venue: "excellent",
      content: "good",
      organization: "excellent",
      overall: "very good",
    },
    recommendation: "yes",
    comments: "Beautiful venue and great atmosphere. Enjoyed meeting industry leaders and the dinner was delicious.",
    improvements: "More interactive sessions would be nice.",
    submittedAt: "2024-08-31T23:30:00Z",
  },
  {
    id: "f7",
    eventId: "4",
    participantId: "p13",
    participantName: "Karen White",
    participantEmail: "karen@example.com",
    rating: 5,
    feedbackCategories: {
      venue: "excellent",
      content: "excellent",
      organization: "excellent",
      overall: "excellent",
    },
    recommendation: "yes",
    comments: "Outstanding pitch competition! The quality of startups was impressive and the judging process was fair and thorough.",
    improvements: "Consider having more time for Q&A after each pitch.",
    submittedAt: "2024-07-16T11:20:00Z",
  },
  {
    id: "f8",
    eventId: "4",
    participantId: "p14",
    participantName: "Liam Garcia",
    participantEmail: "liam@example.com",
    rating: 4,
    feedbackCategories: {
      venue: "good",
      content: "excellent",
      organization: "good",
      overall: "very good",
    },
    recommendation: "yes",
    comments: "Great platform to showcase our startup. Got valuable feedback from investors and made important connections.",
    improvements: "The time slots were a bit tight for thorough presentations.",
    submittedAt: "2024-07-16T15:10:00Z",
  },
];

export {};
